---
- name:
  hosts: config_master
  connection: httpapi
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3


  tasks:

    - name: "Get dirs (groups) in cert/{{ inventory_hostname }}"
      find:
        paths: "./cert/{{ inventory_hostname }}"
        recurse: no
        file_type: directory
      register: found_directories

    - include_tasks: tasks/deploy_cert_group_and_ssl_prof.yml
      with_items: "{{ found_directories.files }}"
      vars:
        cert_dir: "{{ cert_groups_dir.path }}"
      loop_control:
        loop_var: cert_groups_dir
      register: upload_cert_res
