---
- name:
  hosts: config_master
  connection: httpapi
  gather_facts: false
  tasks:

    - name: "Get dirs (groups) in cert/{{ inventory_hostname }}"
      find:
        paths: "./cert/{{ inventory_hostname }}"
        recurse: no
        file_type: directory
      register: found_directories

    - include_tasks: tasks/deploy_cert_group_and_ssl_prof.yml
      with_items: "{{ found_directories.files }}"
      vars:
        cert_dir: "{{ item.path }}"
      register: upload_cert_res
